services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mvp_database}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 5174
      DB_HOST: db
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-mvp_database}
      DB_DIALECT: postgres
      DB_PORT: 5432
      JWT_SECRET: devsecret
      JWT_REFRESH_EXPIRATION: 86400
      JWT_EXPIRATION: 3600
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
      SYNC_ALTER: "true"
    ports:
      - "5174:5174"
      - "5173:5173"
    volumes:
      # монтируем весь код (сервер + фронт)
      - .:/app
      # отдельные кеши node_modules, чтобы не пересобирать на каждый старт
      - app_node_modules:/app/node_modules
      - app_front_node_modules:/app/frontend/node_modules
    command: >
      bash -lc "
        # сервер в watch-режиме
        nodemon --watch app --watch server.js --ext js,mjs,json --signal SIGTERM server.js
      "
    depends_on:
      - db

  # опционально — Vite в отдельном сервисе (если хочешь HMR внутри Docker)
  vite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/frontend
    environment:
      NODE_ENV: development
      VITE_PORT: 5173
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - app_front_node_modules:/app/frontend/node_modules
    command: >
      bash -lc "npm run dev"
    depends_on:
      - app

volumes:
  pg_data_dev:
  app_node_modules:
  app_front_node_modules:
